version = "3.9.4"
runner.dialect = scala36

maxColumn = 120
align.preset = most
newlines.beforeMultilineDef = fold
newlines.topLevelStatements = [before]
newlines.implicitParamListModifierForce = [before]
continuationIndent.defnSite = 2
continuationIndent.extendSite = 2
optIn.breakChainOnFirstMethodDot = true
includeCurlyBraceInSelectChains = true
danglingParentheses.preset = true
rewrite.rules = [
  RedundantBraces,
  RedundantParens,
  SortModifiers,
  PreferCurlyFors
]