datastax-java-driver.advanced.reconnect-on-init = true

akka {
  loglevel = "DEBUG"

  http {
    server {
      # The default value of the `Server` header to produce if no
      # explicit `Server`-header was included in a response.
      server-header = akka-http/${akka.http.version}

      # The time after which an idle connection will be automatically closed.
      idle-timeout = 60s

      # Defines the default request-timeout
      request-timeout = 20s

      # The time period within which the TCP binding process must be completed.
      bind-timeout = 1s
    }
  }

  # Dispatcher configuration
  dispatchers {
    # Dispatcher for Akka HTTP
    http-dispatcher {
      type = Dispatcher
      executor = "thread-pool-executor"
      thread-pool-executor {
        fixed-pool-size = 32
      }
      throughput = 1
    }
  }

  persistence {
    journal {
      plugin = "akka.persistence.cassandra.journal"
      auto-start-journals = ["akka.persistence.cassandra.journal"]
    }

    snapshot-store {
      plugin = "akka.persistence.cassandra.snapshot"
    }

    cassandra {
      journal {
        keyspace = "akka"
        table = "messages"
        keyspace-autocreate = true
        tables-autocreate = true

        # Write consistency level
        write-consistency = "QUORUM"
        read-consistency = "QUORUM"
      }

      snapshot {
        keyspace = "akka_snapshot"
        table = "snapshots"
        keyspace-autocreate = true
        tables-autocreate = true
      }
    }
  }

  actor {
    serializers {
      jackson-json = "akka.serialization.jackson.JacksonJsonSerializer"
    }

    serialization-bindings {
      "akka.serialization.jackson.JsonSerializable" = jackson-json
    }

    persistence-dispatcher {
      type = Dispatcher
      executor = "fork-join-executor"
      fork-join-executor {
        parallelism-min = 8
        parallelism-factor = 3.0
        parallelism-max = 64
      }
      throughput = 5
    }
  }
}